import os
import logging
import uvicorn
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from agent_engine import PharmaAgentEngine

# ==========================================
# 1. Global Logging Configuration
# ==========================================
logger = logging.getLogger("PharmaAgent")

# ==========================================
# 2. FastAPI Instance & Static Mounts
# ==========================================
app = FastAPI(
    title="Pharma-Agent Enterprise API (Stable V3.1)",
    description="Multi-agent system supporting local RAG, PubMed retrieval, and autonomous data analytics.",
    version="3.1.0"
)

os.makedirs("clinical_data", exist_ok=True)
app.mount("/clinical_data", StaticFiles(directory="clinical_data"), name="clinical_data")

agent_engine = PharmaAgentEngine()

# ==========================================
# 3. Data Models (Pydantic)
# ==========================================
class AgentQueryRequest(BaseModel):
    question: str = Field(..., description="The medical query or data analysis instruction.")
    session_id: str = Field(default="default_session", description="Tenant session identifier for state isolation.")

class AgentQueryResponse(BaseModel):
    answer: str = Field(..., description="The final Markdown report generated by the Agent.")
    session_id: str = Field(..., description="Current session identifier.")

# ==========================================
# 4. Core Routing Endpoint (Synchronous)
# ==========================================
@app.post("/agent/chat", response_model=AgentQueryResponse)
def agent_chat_endpoint(request: AgentQueryRequest) -> AgentQueryResponse:
    """
    Synchronous endpoint initiating the LangGraph state machine.
    Blocks until the entire multi-agent workflow completes, returning a final JSON payload.
    """
    logger.info(f"[ROUTER] POST /agent/chat accessed by session: {request.session_id}")
    
    final_report = agent_engine.chat(question=request.question, thread_id=request.session_id)
    
    return AgentQueryResponse(
        answer=final_report,
        session_id=request.session_id
    )

if __name__ == "__main__":
    logger.info("[SYSTEM] Starting Uvicorn server on http://127.0.0.1:8000...")
    uvicorn.run("api:app", host="127.0.0.1", port=8000, reload=True)